### ISSUE TITLE
Suki dashboard disable default elements

### ISSUE THREAD

**Issue by worldsdream** [sukiwp/suki#117]
Hi,

Why can we only enable/disable pro elements and not the ones in the free version?

For example: I like to disable google fonts elements. This is not possible (greyed out). 

There might be a reason why you did that. But, it would be great if we could also enable/disable the default elements in the dashboard. 

Thanks!

**Comment by daviedR** [comment]
Hi @worldsdream 

Thanks for the feedback.

This feature idea is already on our backlog, but it's currently not in our high priority list.

We haven't implement this because there are some core modules that are mandatory, like Header, Footer. It won't make senses to completely disable these kind of modules.

But sure, there are some core modules that are really optional, like Google Fonts, Breadcrumb, Color Palette, etc.

We would see if we can implement this soon.

**Comment by worldsdream** [comment]
Great to hear. Thanks for letting us know that it’s already on the backlog.

I will close this for now.
