### ISSUE TITLE
Controlling Google fonts

### ISSUE THREAD

**Issue by AlchemyUnited** [sukiwp/suki#62]
For the fonts being used, I'm only using a couple styles for each. For example, for the heading font, we're only using bold. 

I suppose I can de-enqueue Suki's font enqueue'ing, and then roll my own - less heavy version  - but maybe there's something already baked into Suki (that I can't find). 

Your thoughts / insights would be appreciated. tia

**Comment by daviedR** [comment]
This has been asked before by our users.

So Suki would automatically call the Google Fonts with all variants.

For example, even if you only use Google Fonts for your heading, e.g. `Open Sans - Bold (700)`, Suki will send a request to this Google Fonts API to include all variants:

`http://fonts.googleapis.com/css?family=Open+Sans%3A100%2C100i%2C200%2C200i%2C300%2C300i%2C400%2C400i%2C500%2C500i%2C600%2C600i%2C700%2C700i%2C800%2C800i%2C900%2C900i&subset=latin`

So you will have a complete list of `font-face` from Google for 100-900 weights and also the italic version. Of course some fonts only supports some weights.

But it shouldn't effect your performance. What I know, browsers would only load the actual font files when the weight is used in the CSS.

So using the example above, your browsers would only load the `Open Sans - 700` file from Google. No other font files are being loaded, if your typography CSS doesn't use other variants.

**Comment by AlchemyUnited** [comment]
@daviedR Thx for the reply.  You said, "But it shouldn't effect your performance. What I know, browsers would only load the actual font files when the weight is used in the CSS."

I'm not so sure that's the case. When you pick a font on fonts.google.com it then lets you customize the faces / weights you want. As you're checking those off fonts.google displays a Load Time estimate. 

As far as I know - looking at the tags / embed fonts.google provides - those fonts are treats as CSS and the browser does not selectively download those. It has no way of knowing. 

But I could be mistaken. These things change all the time. But based on tags / embed I would say my guess is more right than your's :) If you find out otherwise, please let me know. 

So do I have to de-enqueue Suki's fonts for my own?

**Comment by AlchemyUnited** [comment]
FYI - This popped into my inbox

https://rwt.io/typography-tips/variable-fonts-new-google-fonts-api

**Comment by daviedR** [comment]
> As far as I know - looking at the tags / embed fonts.google provides - those fonts are treats as CSS and the browser does not selectively download those. It has no way of knowing.

Did you know that browsers will load the static resources defined in the CSS **ONLY IF** there is an actual element that matches the CSS rule?

For example:

You have CSS that defines the background image for page A and page B. Let's say for page A, you set the background image to be `background-image-A.jpg`, and for page B it's `background-image-B.jpg`.

Currently, you're on page A, the `background-image-A.jpg` is loaded. **BUT** the `background-image-B.jpg` is NOT loaded. Because it's not rendered on the current page.

---

This same behavior is also applied to other static resources that are defined in CSS, including fonts (defined via `font-face`).

To test, you can do the following:

- Set all your headings typography settings to use `Open Sans` with `Bold (700)` weight.
- Suki would automatically make a request to Google Fonts API to return the `font-face` CSS for all variants (the URL automatically requests for 100-900 + italic).
- As you know `Open Sans` has 10 styles: 300,400,600,700,800 + italic, so the returned CSS will contain all `font-face` for 300,300i,400,400i,600,600i,700,700i,800,800i, right?
- Run a test on GTMetrix (or other test services).
- After done, click the **Waterfall** tab.
- Check the **CSS** tab and make sure the returned CSS from Google contain the `font-face` of all available `Open Sans` variants (300,300i,400,400i,600,600i,700,700i,800,800i)
- After that, go to **Fonts** tab, you will see there is **only 1 woff2 file loaded**!
- If you do a cross-check to the returned CSS from Google, the loaded woff2 file is the one defined for `Open Sans - 700`.

If your theory is correct there should be 10 font files loaded for all `Open Sans` variants, right?

The fact, only 1 font file is loaded, because you only use `Open Sans - 700` variant in your page.

---

The only difference is the size of returned CSS from Google Fonts API.

    https://fonts.googleapis.com/css?family=Open+Sans:100,100i,200,200i,300,300i,400,400i,500,500i,600,600i,700,700i,800,800i,900,900i

will have bigger returned CSS compared to:

    https://fonts.googleapis.com/css?family=Open+Sans:700

But the difference is only **tiny bytes**! If you checked the GTMetrix result > Waterfall > CSS. You can see the returned CSS from Google for all `Open Sans` variants is only **1.3KB**!

---

Another benefit why we chose to request all variants `font-face` is:

Sometimes you would use an inline tag like `<strong>` or `<em>`, which means you need to have the font-face for the bold and italic style, right? If you already have the complete `font-face` definition, you will get the proper styling right away.

---

Hope this makes sense to you.

But of course, you can dequeue the Google Fonts CSS from Suki. You can just remove the action hook that we use to enqueue the Google Fonts CSS.

**Comment by daviedR** [comment]
I will mark this issue as resolved for now.

We can still have further discussion on this.
